pipeline {
    agent any

    stages {
        stage('Init') {
            steps {
                cleanWs()
            }
        }

        stage('SCM') {
            steps {
                git 'https://github.com/Alex-Golub/simple-webapp-nodejs.git'
                script {
                    ciConfig = readYaml(file: 'jenkins/ciConfig.yml')
                }
            }
        }

        stage('Build') {
            agent {
                docker {
                    image ciConfig.buildImage
                }
            }
            steps {
                sh "node -v"
                sh 'docker build -t simple-webapp-nodejs:1.0 .'
                sh 'docker images'
            }
        }

        stage('Deploy') {
            steps {
                sh '\
                docker container rm -f simple-webapp-nodejs-container && \
                docker run -itd \
                --name simple-webapp-nodejs-container \
                -p 3000:3000 \
                simple-webapp-nodejs:1.0'
            }
        }
    }
}
